services:
  - type: web
    name: call-osint
    runtime: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8491544250:AAEUCsJ_lT_2oNQWq4CcI0b2-x6g2h_2DvM"
      - key: ADMIN_ID
        value: "5451167865"
      - key: API_KEY
        value: "ft-key-tr-jzynhifn87aq"
      - key: PORT
        value: "5000"
